### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cryptix** [cryptix/trakting#1]
features i want to add
- [ ] query backend for available storage and display at `/upload`
- [ ] delete
- [ ] search
- [ ] comments
- [ ] waveforms
- [x] order by upload date - d065f392584
- [x] filter by user -  adc25068341e8
- [x] change password - bdad5e6728
- [ ] folders/playlists
- [x] database constraints - 52552eb0fd
